# Generated by Django 4.1.4 on 2023-01-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0003_post_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
